apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: copyrators.flant.com
spec:
  group: flant.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          ruleType:
            type: string
          namespace:
            type: string
          selector:
            type: object
            properties:
              copyrator:
                type: string

  scope: Namespaced
  names:
    plural: copyrators
    singular: copyrator
    kind: CopyratorRule
    shortNames:
    - copyr
